[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "pydiffsol"
dynamic = ["version"]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
readme = { file = "README_PyPI.md", content-type = "text/markdown" }
license-files = ["LICENSE", "LICENSE.libunwind", "LICENSE.zstd"]

dependencies = [
    "numpy",
]

[project.optional-dependencies]
dev = [
    "matplotlib",
    "pytest",
]

[tool.maturin]
features = ["pyo3/extension-module"]

# Paths for examples added explicitly for documentation smoke testing
[tool.pytest.ini_options]
testpaths = [
    # FIXME re-enable before merge to main
    #"examples/*.py",
    "test/"
]
